eclipse-mosquitto/mosquitto

service/systemd/README
service/systemd/mosquitto.service.notify
service/systemd/mosquitto.service.simple

Config file is installed by default, so I would expect that it will be used by
the systemd service. Add argument for the configuration to the services.
Signed-off-by: Tomas Novotny <novotny@rehivetech.com>

Add default config path to systemd services.

---

lib/net_mosq.c

In windows OpenSSL sometimes returns SSL_ERROR_SYSCALL on non-blocked socket when connection in progress. This is workaround for this situation.

Workaround for Windows SSL

---

CMakeLists.txt
lib/CMakeLists.txt
lib/cpp/CMakeLists.txt
lib/mosquitto.h
src/CMakeLists.txt

* Now has a `DOCUMENTATION` option for enabling/disabling documentation man pages
* Created a new static library target for libmosquitto, named `libmosquitto_static`
* Remove all function export declarations for the static library
* No longer calls `/sbin/ldconfig` on platforms other than Unix
(this is basically the same as [this PR](https://github.com/eclipse/mosquitto/pull/143))

CMake improvements

---

src/conf.c
src/read_handle_server.c

The use-after-free allows an unauthorized attacker to crash the broker.

Fix use-after-free (DOS) and small memory leak

---

lib/mosquitto_internal.h
src/context.c
src/database.c
src/handle_connect.c
src/mosquitto_broker.h
src/persist.c

Split message queue in two queues: in-flight and queued to avoid the
need to iterate over all messages.
See #140 for complete description. It's the same PR but:
* based on develop instead of master
* using 2 chained-list instead of counter
* with CLA signed :)
About my question on current code, I've assumed that:
* [db__mesage_write](https://github.com/eclipse/mosquitto/blob/62402f7b60c17d9dc074b0ccd53a7a32c906994e/src/database.c#L892) could dequeue all kind of message (not only incoming message) and that max_inflight is for both incoming and outgoing message
* max_inflight should be always check for zero value (unlimited)
* In [db__message_delete](https://github.com/eclipse/mosquitto/blob/62402f7b60c17d9dc074b0ccd53a7a32c906994e/src/database.c#L293), send a pubrec like in …

Improve performance with lots of queued message

---

lib/CMakeLists.txt
lib/cpp/CMakeLists.txt

1. Fix a build fail which is caused by a lack of source object in libmosquitto.
2. Add an CMake option BUILD_STATIC_LIBRARY to allow control over building static libraries or not.
3. Add an CMake option WITH_PIC to allow control over building static libraries with PIC or not.
4. Add build configuration to build CPP static library.

Enhance static library build

---

Mosquitto.podspec

This version is now pushed to CocoaPods:
https://raw.githubusercontent.com/CocoaPods/Specs/beee5c5026a9b374b8ab99066044a55525b1720c/Specs/Mosquitto/1.4.8/Mosquitto.podspec.json

Change pod name to Mosquitto

---

lib/cpp/mosquittopp.cpp

The WITH_* flags are not handed over to the C++ wrapper, instead it relies on
the actual library to check status.
Signed-off-by: Johan de Vries (Ubuntu VM) <devries@wivion.nl>

Fixes a bug where C++ wrapper would always claim SOCKS was not supported

---

src/websockets.c

A lot of function renaming was done in 663d50a0168bfdce98473265fdcece364600340f,
and this websockets patch was merged afterwards.  Autobuild testing
doesn't have websockets enabled, and missed this.
Fixes: d9142c3974be0ef6d4bc3a0aef762f8a7d8e1f32
Signed-off-by: Karl Palsson <karlp@etactica.com>

websockets: fix compile fail after refactoring

---

src/mosquitto_broker.h
src/websockets.c

The context associated with websocket client didn't had listener filled, which caused use_username_as_clientid to be ignored.
This PR replace PR #235

Fix missing context->listener for websocket client

---

src/persist.c

Mosquitto database writes are not atomic and if power is lost during
a write the file will be permanently lost.  This commit makes writes as
atomic as possible.
Signed-off-by: Keegan Callin <kc@kcallin.net>
Bug: https://github.com/eclipse/mosquitto/issues/189

[189] Mosquitto database corrupted on power-loss.

---

src/mosquitto_broker.h
src/websockets.c

patch is against the fixes branch, this was a regression from 1.4.9 to 1.4.10.
See also https://github.com/openwrt/packages/issues/3127
----
In 1.3, 1.4 and 1.5, the function was "libwebsockets_get_protocol" not
"libwebsocket_get_protocol"  While the #define name doesn't matter on
newer libwebsockets, where it redirects to lws_get_protocol, the naming
is critical for older versions.
Fixes: 477cd3e39911 (Fix missing context->listener for websocket client)
Signed-off-by: Karl Palsson <karlp@etactica.com>

websockets: fix compatibility with older lws versions

---

ChangeLog.txt
lib/mosquitto_internal.h
man/mosquitto.8.xml
man/mosquitto.conf.5.xml
mosquitto.conf
src/conf.c
src/context.c
src/database.c
src/mosquitto_broker_internal.h
src/sys_tree.c
test/broker/03-publish-qos1-queued-bytes.conf
test/broker/03-publish-qos1-queued-bytes.py
test/broker/Makefile
test/mosq_test.py
travis-install.sh

First round draft for discussion:  Some of these pieces are independent, such as the test remaining_length fix, and the db_dump tweaks and can clearly be put into separate pull requests.  Three mains changes:
* broker stats on bytes stored, not just counts
* max_queued_bytes setting now (substantially easier to limit the memory consumed by each client)
* queue_qos0_messages fixed to not infinitely queue.
Questions:  
* Should max_inflight_bytes be documented out and user tunable?  Probably for consistency?
* I had to publish initial load average stats to make it sane for parsing the $SYS tree for testing.  It's still very hard to automatically test some of this, without access to the client level queue stats from the tests.  The broker bytes store is influenced not just by messages to …

Implement byte limits for message queues

---

CMakeLists.txt
libmosquitto.pc.in
libmosquittopp.pc.in

This patch adds pkg-config files for libmosquitto and libmosquittopp,
and installs them through CMake.
Refs #107

Add pkg-config files to CMake build

---

src/websockets.c

Check current number of connections before accepting new websockets clients.
Signed-off-by: tucic <tucic.milan@gmail.com>

Maximum connections for websockets listener

---

man/mosquitto.conf.5.xml
src/bridge.c
src/conf.c
src/handle_connack.c
src/mosquitto_broker_internal.h

This update adds an option to only publishes bridge
notification messages to the local side of the bridge.
It adds a config file option called notifications_local_only
that accepts a boolean value, defaults to false to be
consistent with existing behaviour.
Fixes #233
Signed-off-by: Ben Hardill <hardillb@uk.ibm.com>

Add support for local only bridge notifications

---

lib/cpp/mosquittopp.h

A modern version of the clang compiler complained about:
* unused parameters
* additional semicolon
. This commit fixes these warnings.
Signed-off-by: Jens Breitbart <jbreitbart@gmail.com>

Fix compiler warnings (unused parameter, additional semicolon).

---

docker/1.4.4/Dockerfile
docker/1.4.8/Dockerfile

When installing the Mosquitto package from Alpine Linux, we don't need
to save the latest package index to the cache. We are specifically requesting
the latest package index each time we install Mosquitto and not using the local
cache at all (--no-cache).

Update Dockerfiles to not save apk cache

---

docker/1.4.10/Dockerfile
docker/1.4.10/README.md
docker/1.4.10/docker-entrypoint.sh

Basically the Dockerfile has been adapted to inherit from the alpine 3.5 image and to install the 1.4.10-r2 version of mosquitto.

Added docker support for version 1.4.10-r2 based on alpine 3.5

---

src/CMakeLists.txt

Fix the following error:
[ 98%] Linking C executable mosquitto
CMakeFiles/mosquitto.dir/security.c.o: In function `mosquitto_acl_check':
security.c:(.text+0x159d): undefined reference to `mosquitto_client_username'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/mosquitto.dir/build.make:1215: src/mosquitto] Chyba 1
make[1]: *** [CMakeFiles/Makefile2:483: src/CMakeFiles/mosquitto.dir/all] Chyba 2
make: *** [Makefile:128: all] Chyba 2

Add (missing) plugin.c into build

---

lib/net_mosq.c
lib/tls_mosq.c

Signed-off-by: Jiří Pinkava <j-pi@seznam.cz>
This adds more verbose logging for case when TLS error occures during connection. This is especially aimed in case where CN in server certificate does not match server hostname and 'insecure_tls' option is disabled (default).
Without this error logging messages client (eg. mosquitto_pub) says nothing useful and server only says "Internal SSL error".
This happens when someone creates certificates as described in mosquitto-tls and uses mosquitto server with default example configuration. I suppose this might happens quite often. Debuging this is pretty hard and requires to dwelling deep in source code.

Log more TLS error details

---

lib/net_mosq.c
src/net.c

I believe the problem is related to clearing the SSL error queue before the appropriate SSL call. I added this clearing before each call whose error status is then probed and it seems that it solved the issue for us.

 #419 Broker sometimes kills connection to client

---

src/loop.c
src/websockets.c

I've seen two issue with Websocket introduced by c07ba2a:
* As soon as a Websocket client is connected, Mosquitto eat 100% CPU
* If a Websocket client publish a "large" message (4096 seem to be the threshold), the message is never received by the broker and connection get stuck.
Seen this on fixes branch with libwebsocket 1.7.3.
Run Mosquitto (fixes branch, to include commit c07ba2a):
```
cat > mosquitto.conf << EOF
listener 1888
protocol websockets
log_type all
EOF
mosquitto -c mosquitto.conf
```
Using Python client:
```
import logging
logging.basicConfig(level=logging.DEBUG)
import paho.mqtt.client as mqttc
client = mqttc.Client(transport='websockets')
client.enable_logger()
client.connect('localhost', 1888)
client.loop_start()
```
We seen that client connect correctly (both Mosquitto …

Fix two issues with Websocket

---

src/loop.c

From http://man7.org/linux/man-pages/man3/getdtablesize.3.html:
"It is not specified in POSIX.1; portable applications should employ
sysconf(_SC_OPEN_MAX) instead of this call."
Specifically this fixes a build failure on Android which does not
have getdtablesize().

Replace getdtablesize() with sysconf(_SC_OPEN_MAX)

---

test/broker/11-persistent-subscription.conf
test/broker/11-persistent-subscription.py
test/broker/Makefile

The PR add test for persistent subscription.
This test show a bug currently present in develop branch (and not in master).
The issue is that subscription are not correctly persisted in the database. Without the test, we can reproduce the bug with:
```
$ cat mosquitto.conf 
persistence true
listener 1888
$ rm -f mosquitto.db
$ ./mosquitto -c mosquitto.conf&
$ ./client/mosquitto_sub -p 1888 -q 1 -t thetopic -c -i test   # Stop it as soon as it connected to broker
$ ./client/mosquitto_pub -p 1888 -q 1 -t thetopic -m "message sent before restart"
$ ./mosquitto -c mosquitto.conf&
$ ./client/mosquitto_pub -p 1888 -q 1 -t thetopic -m "message sent after restart (not received)"
$ ./client/mosquitto_pub -p 1888 -q 1 -t " /thetopic" -m "message sent after restart on another topic"
$ …
```

Add test for persistent subscription

---

docker/1.4.14/Dockerfile
docker/1.4.14/README.md
docker/1.4.14/docker-entrypoint.sh

As I encounter issue with 1.4.12, I needed to test with 1.4.14
Here is a pull request based on alpine:edge
please note that for reason that I ignore, docker-entrypoint.sh didnt wanted to run before I added specific permission, which isnt in your version.

support for 1.4.14 into docker

---

config.mk
lib/mosquitto_internal.h
src/loop.c
src/mosquitto_broker_internal.h

Sorry for #484 closed accidentally.
Merged current develop branch and remade pull-request.
-----------------------------
Added epoll for Linux.
Using epoll system-call instead of poll, mosquitto can get performance improvement especially in handling huge concurrent connections. I confirmed it on my test environment.
Compile option: "$ make binary WITH_EPOLL=yes" to try.
Signed-off-by: Tatsuzo Osawa (toast-uz)

Add Epoll.

---

Makefile
client/Makefile
lib/Makefile
lib/cpp/Makefile
man/Makefile
src/Makefile

This prevents failures during make install when whitespace
is part of DESTDIR pathname.
Signed-off-by: Michael Heimpold <michael.heimpold@i2se.com>

Quote ${DESTDIR} usage in various Makefiles

---

src/websockets.c

When client over WebSockets fail to authenticate, the CONNACK packet was
not sent because the connection was closed too early. Closes #18.
non-WebSockets connection don't have this issue because call to [_mosquitto_send_connack](https://github.com/eclipse/mosquitto/blob/a4e912079fd399dd1c6f7080e27d51787530a4bb/src/read_handle_server.c#L398) will write immediately to the socket ([code](https://github.com/eclipse/mosquitto/blob/a4e912079fd399dd1c6f7080e27d51787530a4bb/lib/net_mosq.c#L177)).
For Websockets, the packet is only queued, but since rc != 0, connection is closed because writable callback could be called ([code](https://github.com/eclipse/mosquitto/blob/a4e912079fd399dd1c6f7080e27d51787530a4bb/src/websockets.c#L389)).
This PR change this behavior: when rc != 0, the socket is not …

Fix CONNACK not send over WebSocket for bad auth

---

lib/net_mosq.c

Fix issue when SSL_connect() returns SSL_ERROR_WANT_READ. A call to SSL_write here will later transmit a new client hello and make ssl connection fail.
Se issue #608#
Signed-off-by: JonoJensen <jono.jensen@yahoo.se>

Fix issue when SSL_connect() returns SSL_ERROR_WANT_READ.

---

src/websockets.c

Commit 7943072b1f3b (Fix use_identity_as_username not working on websockets
clients) added code which unconditionally accesses mosq-ssl, breaking the
build when TLS support is disabled.
Fix it by guarding this logic inside #ifdef WITH_TLS.
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>

websockets.c: unbreak build without TLS

---

snap/default_config.conf
snap/launcher.sh
snap/mosquitto.conf
snap/snapcraft.yaml

This PR allows the loading of config from a user writable area on disk.  $SNAP_USER_COMMON is not versioned on upgrades, and so the user's config will remain the same across upgrades.
I've created a new "default_config.conf" file based on the config that was being shipped inside the snap directory (and removed the mosquitto.conf file).  The launcher script will fall back to this file if there isn't a user config file in the specified location.  This should mean that when run, the snap will actually do something useful.  I dropped "user root" from this example, as I don't think that it needs to run as root, but I might be wrong.  It seems to work ok here.
The launcher script first copies the example config (from the root of the source) in to the $SNAP_USER_COMMON directory, so that people …

Use config from user writable snap directory

---

src/websockets.c

If you use websockets without OpenSSL / TLS support, you don't compile mosquitto.
This fix propose to resolve this problem.
THX
Signed-off-by: Tifaifai Maupiti <tifaifai.maupiti@gmail.com>

Fix: use websockets without OpenSSL / TLS.

---

src/database.c

inside the `if(!temp->payload)` branch, the statement `if(temp->payload) _mosquitto_free(temp->payload);` is dead code.

remove dead code

---

lib/net_mosq.c

When trying to connect to MQTT over SSL on Windows the broker immediately disconnects the client.
Debugging shows the issue is that _mosquitto_net_read sets the errno variable to EAGAIN, but the code at the calling side in _mosquitto_packet_read overwrites the value assigning WSAGetLastError() on Windows platform. The WSAGetLastError() indicates no failure, but the following code does not expect that value.
The fix is to put back the altered errno using WSASetLastError() so that it can be picked up again.

Fix SSL on Windows

---

service/systemd/mosquitto.service.notify
service/systemd/mosquitto.service.simple

Updated the unit file examples to add a dependency on the
network-online.target systemd target to prevent mosquitto from
starting without network connectivity.
Added a documentation line to the unit files pointing to mosquitto
manpages.
Signed-off-by: Rich Mattes <richmattes@gmail.com>

Add documentation and networking dep to unit files

---

src/context.c
src/handle_connect.c
src/handle_publish.c
src/handle_subscribe.c
src/mosquitto_broker_internal.h
src/security.c
src/subs.c

All fields in mosquitto_acl_msg wasn't filled before call to plugin.  
I'm not sure if there is another way this should be fixed, but i thought that i'd just add the missing struct fields through parameters to the mosquitto_acl_check call.

add missing paramters to internal mosquitto_acl_check

---

src/mosquitto_passwd.c

Make sure the prompt is actaually printed by flushing stdout when asking
for passwords.

Flush stdout when asking for password.

---

src/database.c
src/mosquitto_broker_internal.h
src/subs.c

Revised #531 for v1.5-fixes.
Rearranged subhier relation architecture and fixed memory issue #505 .
#505 is such a critical issue remained v1.5 that should be solved asap.
Signed-off-by: Tatsuzo Osawa (toast-uz)

Fix subs memory issue. (for v1.5-fixes)

---

src/signals.c

The signal handler thread on win32 did listen to 4 HANDLEs,
of which only 3 were initialized.
The result was 1 thread eating 100% cpu.
This commit reduces the HANDLE array storage.
Signed-off-by: Kurt Van Dijck <dev.kurt@vandijck-laurijssen.be>
-----

fix signal handler on win32

---

CONTRIBUTING.md

Changed links for signing ECA as these were outdated and fixed indentation issue.
Signed-off-by: Vinod Kumar <kumar003vinod@gmail.com>
-----

update links for signing ECA, fix indentation

---

src/conf.c

`conf__parse_bool` returns `MOSQ_ERR_INVAL` even if boolean value in mosquitto config file is invalid. This causes unexpected behaviour, for example if we run mosquitto with `persistence t` mosquitto prints error in logs but starts successfully without persistence.
```
$ mosquitto -c mosquitto.conf
Error: Invalid persistence value (t).
1538079039: mosquitto version 1.5.1 starting
1538079039: Config loaded from mosquitto.conf.
1538079039: Opening ipv6 listen socket on port 1883.
1538079039: Opening ipv4 listen socket on port 1883.
```
If mosquitto is running with persistence and config is changed, on reload signal mosquitto will print error message, but it will take the default value of persistence and persistence will be disabled.
Signed-off-by: Vinod Kumar <kumar003vinod@gmail.com>
-----

return MOSQ_ERR_INVAL if config has invalid boolean value

---

src/loop.c

All tests ran, except for:
08-tls-psk-pub.py
08-tls-psk-bridge.py
Which didn't complete after leaving them running for 15 minutes each.
This fixes https://github.com/eclipse/mosquitto/issues/1019

fix bug where bridge doesn't honor restart_timeout setting

---

lib/loop.c

Hi,
``mosquitto_loop_read()`` sometimes doesn't read all the packets when I use it with TLS and an external loop. This PR fixes this issue.
-----

Check SSL_DATA_PENDING in mosquitto_loop_read()

---

lib/packet_mosq.c

Change was part of the original commit e8185ddaa74234c2c37aa529e711cddfc7cede91
"[166] Don't cancel external threads."
and then lost during code reorganizing and subsequent merge,
commits 970ba58da63b2790607585edcc364b7ada614e3b 81cb7ab547b37edcdf9e22e2ab93cbe260bb924b
Signed-off-by: Maksym Ruchko <mruchko@advantech-bb.com>
-----

Fixed threaded enum lost in merges

---

src/conf.c

This is a fix I am proposing for #1075 . The inline comment does not work for configuration parameters which have optional values. like `listener port [bind address/host]`.
In such cases currently we read inline comment as optional parameter value. This patch just ignores the inline comments and default value of optional params is used.
In this patch I have considered `listener`, `address` and `topic` as these have optional parameters in configuration file (I hope I did not miss any).
Other approach could be to display proper error message, but for other configuration keys where we do not have optional parameters we end up ignoring inline comments, because we do not parse the line once we get the required values, so this will make it consistent across the whole config.
This will not work …

ignore inline comments while parsing optional config params

---

lib/net_mosq.c

Previous behaviour would clear the external SSL_CTX provided by
MOSQ_OPT_SSL_CTX. This required the user to reset the SSL_CTX every
disconnect, and trust that they were not leaking references.
Recreating the SSL context for every connection is not necessary, and the
SSL context is freed in mosquitto_destroy, which is sufficient.
Signed-off-by: Matthias Stone <matthias@bellstone.ca>
-----

Don't clear SSL context when TLS connection is closed.

---

src/websockets.c

Without this, mosquitto doesn't build on FreeBSD with websockets enabled
Signed-off-by: Steven Lawrance <stl@koffein.net>

Fix missing AF_INET definition

---

client/client_shared.c

Signed-off-by: Till Zimmermann <tzimmermann@uni-osnabrueck.de>
This fixes a Segmentation Fault in the client tools I encountered recently when supplying a malformed URL to the `-L`-Flag (missing trailing `/`) (cf. #1248).
-----

Fixed Segmentation Fault / NULLptr dereference

---

lib/net_mosq.c
lib/options.c
src/net.c

Not sure if the ui.h include is part of engine support or not, but it needs to be included for the openwrt buildroot at least.
The ENGINE=no support is just something quick to get me to compile again.  I may have not taken the preferred paths of warning that things might not be available.
I'm _completely_ ok with simply requiring ENGINE support.  OpenWrt is defaulting to engine ON now, I've only extended the patching as support for building without engine support was already in the codebase.
- [n/a ] If you are contributing a new feature, is your work based off the develop branch?
- [no (fixes branch isn't uptodate) ] If you are contributing a bugfix, is your work based off the fixes branch?
- [x ] Have you added an explanation of what your changes do and why you'd like us to include …

Ssl fixes for ENGINE and UI includes

---

src/security.c

If you've had authentication plugin version 4 the broker would never call `mosquitto_auth_psk_key_get` because there was an incorrect version check. 
Signed-off-by: Matevz Mihalic <matevz.mihalic@gmail.com>
-----

Fix plugin psk_key_get for v4

---

config.h
lib/mosquitto.c
lib/thread_mosq.c

-----
pthread_cancel() is not available on Android
Thus mosquitto_loop_start() and mosquitto_loop_stop()  won't be available there (and mosquitto_connect_async() as a consequence).

No pthread_cancel() on Android

---

client/pub_client.c
client/rr_client.c
client/sub_client.c

the `memset(&cfg, 0, sizeof(struct mosq_config));` already exsits in
`client_config_load()`'s `init_config()`. So calling it in main function
is totally unnecessary.
-----

Remove redundant initialization in clients

---

src/mosquitto_passwd.c

This handles some inconsistencies in mosquitto_passwd.c . The MAX_BUFFER_LEN was not used at all places, which could result in a buffer overflow in case of MAX_BUFFER_LEN != 1024 here:
https://github.com/eclipse/mosquitto/blob/995f90dbafa82c7fd3d24f7174d094f11c2d6c85/src/mosquitto_passwd.c#L529
Also `strncpy` does not garantee to produce a Null-terminated string in destination, if src is longer than the third parameter `len`:
https://github.com/eclipse/mosquitto/blob/995f90dbafa82c7fd3d24f7174d094f11c2d6c85/src/mosquitto_passwd.c#L367
Due to the special case that MAX_BUFFER_LEN is set to 1024, this is not a critical bug, but now it should be safe to change MAX_BUFFER_LEN if necessary.
As I do not have a working OpenSSL-Setup, I'm unable to test it myself. But I hope the CI will do it. …

Fix password input when MAX_BUFFER_LEN is not 1024 in mosquitto_passwd.c

---

client/client_shared.c

free() would take no action if the arguement is a NULL pointer.
Therefore, the if statement is totally unnecessary.
See ISO-IEC 9899
Signed-off-by: YangHau <vulxj0j8j8@gmail.com>
-----

feat: Remove unecessary if statement

---

src/db_dump/db_dump.c

If statement for detecting if a pointer is NULL is totally unnecessary.
As what it did in #1365 
Signed-off-by: YangHau <vulxj0j8j8@gmail.com>
-----

Remove useless if statement

---

man/mosquitto_pub.1.xml

Should $HOME/.config/mosquitto_sub be $HOME/.config/mosquitto_pub? It seems to be that way based on my testing.
I think this is a copy/paste error.
I'm not doing an ECA for this.  It is one letter.

$HOME/.config/mosquitto_sub or pub?

---

src/bridge.c

The current implementation does not properly forward the engine
parameters to OpenSSL causing OpenSSL to incorrectly attempt to open the
engine key uri as a file.
This fix enables net_mosq.c:net__init_ssl_ctx to use ENGINE_load_private_key instead of SSL_CTX_use_PrivateKey_file.
Signed-off-by: Matt Woelfel <matt@woelfware.com>

Fix usage of tls_engine and tls_keyform.

---

test/broker/01-connect-invalid-reserved.py
test/broker/02-subpub-qos2.py
test/broker/07-will-null-topic.py
test/mosq_test.py

-----
Hi,
This fixes some issues I spotted while working on acceptance tests.
This is my first pull request on Github, I think I made everything properly but do not hesitate to tell me if this is not the case.

Fix send pkt

---

client/pub_client.c

Main loop has two different logic inside: one for stdin input,
second for all other cases. Exit loop condition is also different
for both variants. This commit splits these two variants into
two separate loops.
It could help fixing other issues in this part of code and greatly improve it's readability.
There are also a little clean-up things:
- use `rc` in stdin loop, so we get exit status and spare few bytes
- use MOSQ_ERR_SUCCESS instead of cryptic `0`
Signed-off-by: Marek Wodzinski <majek@w7i.pl>
-----

mosquitto_pub: split main loop.

---

ChangeLog.txt
client/pub_client.c

Since 1.6.3 'mosquitto_pub -l' frequently hangs after end of stdin.
This fix allows to run disconnection part of code before leaving loop, so clean mqtt end of session is possible.
Fixes #1448.
Signed-off-by: Marek Wodzinski <majek@w7i.pl>
-----

Fix `mosquitto_pub -l` hang when stdin stream ends. Closes #1448.

---

CMakeLists.txt

libmosquitto.pc and libmosquittopp.pc contain arch dependent information.
The Makefile based build already does this correctly.
Signed-off-by: Timo Gurr <timo.gurr@gmail.com>

Install pkg-config files into arch dependent locations also for CMake builds

---

client/sub_client.c

Fixes #1513 
Signed-off-by: Basavesh Shivakumar <basavesh.shivakumar@gmail.com>
- [N/A] If you are contributing a new feature, is your work based off the develop branch?
- [Y] If you are contributing a bugfix, is your work based off the fixes branch?
- [Y] Have you added an explanation of what your changes do and why you'd like us to include them?
- [Y] Have you successfully run `make test` with your changes locally?
- [Y] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [Y] Do each of your commits have a "Signed-off-by" line, with the correct email address? Use "git commit -s" to generate this line for you.
-----

In sub_client.c, call mosquitto_destroy() in cleanup label.

---

lib/util_mosq.c

Reason: There is no check that the mosquitto__malloc at line 162 was sucessfull.
This could result to a Null pointer dereference in the memcpy call at line 166.
Fix: I added the check.
Signed-off-by: Panagiotis Vasilikos <panagiotis.vasilikos@alexandra.dk>

Potential Null pointer dereference in util_mosq.c

---

lib/socks_mosq.c
src/handle_unsubscribe.c

Memory leak in socks_mosq.c
Reason: The memory allocated for the packet pointer at line 155 is not freed
before returning at line 188.
Fix: I inserted the mosquitto__free(packet) statement just before returning
at line 188.

Bugfix mem leak in socks

---

lib/socks_mosq.c
src/handle_unsubscribe.c

Memory leak in handle_unsubscribe.c
Reason: In line 70, the memory allocation for the pointer "reasons_codes" may 
result to a memory leak due to the many returns (e.g as the one in line 78)
occuring in the program's path until reaching the mosquitto__free at line 122.
Fix: I added a mosquitto__free(reason_codes) statement before each return
statement that could result to a memory leak.
Signed-off-by: Panagiotis Vasilikos panagiotis.vasilikos@alexandra.dk

Bugfix mem leak in handle unsubscribe

---

lib/connect.c
lib/loop.c
lib/mosquitto.c
lib/net_mosq.c

sleep was blocking loop_stop(force=false) since it
was uniteruptible
Signed-off-by: Christian Schneider <cschneider@radiodata.biz>
--> How?
-----

fix: replace sleep with (p)select in loop_forever

---

man/mosquitto.conf.5.xml
src/bridge.c
src/conf.c
src/context.c
src/database.c
src/mosquitto_broker_internal.h
test/broker/06-bridge-b2br-disconnect-qos1.py
test/broker/06-bridge-clean-session.py
test/broker/Makefile
test/broker/test.py
test/mosq_test.py

This is allows separating bridge clean session settings between the
local and remote endpoints.  Some broker implementations refuse to allow
non-clean sessions, as they don't support storing messages to be sent to
the connecting broker.  However, this doesn't meant that the local
broker can't be queueing messages to send _out_ to the remote broker.
This PR adds a new bridge connection setting, local_clean_session, that
allows controlling this split.
All ready now (I think)
- [] Have you successfully run `make test` with your changes locally?
no, but the test failure doesn't appear related to my code change.
and tests are added for the new features
-----

support bridge local clean session

---

lib/mosquitto.c

Add a refcount around mosquitto_lib_init and mosquitto_lib_cleanup so that multiple calls to init/cleanup don't trigger memory leaks or double-frees.
Another for this change is the following scenario that I have:
- I have a library that internally uses mosquitto to subscribe to notifications.
- Applications want to use mosquitto to publish notifications.
- If both my library and applications call mosquitto init/cleanup, valgrind reports a memory leak, as the memory is clobbered in the second init call.
The only current solution is that the library requires the application to call mosquitto init/cleanup prior to initializing the library. However, it would be nice if instead both application and library could call init/cleanup and things would "just work" no matter what, especially as many …

add a refcount to library init/cleanup

---

lib/mosquitto.h

We currently erroneously claim that mosquitto_lib_init cannot fail,
while it can fail on Windows, if WSAStartup fails in net__init. Correct
this.
"make test" is failing on my machine, but it fails identically on the fixes branch (on `./02-subscribe-qos1.py`). As this changes only documentation, I highly doubt that's the issue.
Test failure:
```
./02-subscribe-qos1.py c/02-subscribe-qos1-async2.test
connect_async failed: Connection refused
Traceback (most recent call last):
File "./02-subscribe-qos1.py", line 47, in <module>
(conn, address) = sock.accept()
File "/usr/lib/python3.8/socket.py", line 292, in accept
fd, addr = self._accept()
socket.timeout: timed out
make[2]: *** [Makefile:36: c] Error 1
make[2]: Leaving directory '/home/martin/ws/mosquitto/test/lib'
make[1]: *** [Makefile:11: …
```

correct mosquitto.h return code documentation

---

client/sub_client_output.c

Changes made a couple of weeks ago broke WITH_CJSON=no builds. This patch fixes that issue on develop (the fixes branch is out of sync with develop, at least for this file).
The fixes branch seems to be out of sync, so I created the pull request to develop. Please advice if rework is needed, and how to proceed.
-----

remove cjson stranded reference when building WITH_CJSON=no

---

docker/generic/Dockerfile

Signed-off-by: matt <swineherd92@gmail.com>
- [ y] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [ y] Do each of your commits have a "Signed-off-by" line, …

replace unavailable ssl libs in the generic dockerfile with openssl

---

src/mosquitto.c

Before this commit there was no good way to detect that the
Mosquitto broker was done with its startup phase on systems
without systemd.
On such systems it was tricky to e.g. start the broker from
a test where ports are dynamically assigned and one have to
deal with potential port conflicts.  Without a way to know
that the broker is done with its startup phase, there was no
way to know if the broker was able to acquire the port (for
both IPv4 and IPv6) without waiting for some unknown period
of time (when many tests are run in parallel a single process
might be starved for resources).
With this new broker ready message it is easy for the parent
process to monitor the broker output and figure out when the
port was successfully acquired.
Signed-off-by: Sigmund Vik <sigmund_vik@yahoo.com> …

Add broker ready message.

---

src/sys_tree.h

This fixes Visual Studio compiler warnings like this one:
"warning C4003: not enough arguments for function-like
macro invocation 'G_MSGS_DROPPED_INC'"
Signed-off-by: Sigmund Vik <sigmund_vik@yahoo.com>
-----

Fix sys_tree macro stubs with no arguments.

---

src/net.c
src/security.c
src/service.c

From the FormatMessage() Win32 API documentation: "The lpBuffer
parameter is a pointer to an LPTSTR; you must cast the pointer
to an LPTSTR (for example, (LPTSTR)&lpBuffer)."
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessage#parameters
This commit fixes warnings like these:
warning C4047: 'function': 'LPSTR' differs in levels of indirection from 'char **'
warning C4024: 'FormatMessageA': different types for formal and actual parameter 5
Signed-off-by: Sigmund Vik <sigmund_vik@yahoo.com>
-----

Fix FormatMessage warnings for Windows.

---

src/mux_epoll.c

In the mux_epoll__add_in function, no context->events was set. Previously this was set to match the ev.events (EPOLLIN). Adding this back in, keeps the code consistent to before it was refactored to split out epoll and poll functions, as well as being consistent with the other mux_epoll__ functions.
If this is not set, the connection is never fully established when the broker comes back up.
Fixes #1680.
Signed-off-by: Simon Tate <simon.tate@bt.com>
fix/feature change in an issue. …

Fix bridge reconnect

---

lib/net_mosq.c
lib/net_mosq.h
src/net.c

Signed-off-by: Abilio Marques <abiliojr@gmail.com>
Currently, when using a WITH_TLS compiled version of the mosquitto library, it will automatically initialize openssl as mosquitto_lib_init gets called. This causes > 120 Kb of RAM to be allocated, even if not needed (e.g., connecting to local broker, via TCP or UNIX sockets).
This patch allows for SSL to be initialized when it's needed. Broker functionality remains unchanged.
-------------------------------------------------------------------------------------------------------------
-----

lazy init SSL for libmosquitto

---

lib/thread_mosq.c

This fixes the following error, when compiling for systems without
pthread support, and when passing WITH_THREADING=no to make:
thread_mosq.c:24:12: fatal error: pthread.h: No such file or directory
^~~~~~~~~~~
compilation terminated.

do not include pthread when compiling without threading support

---

lib/linker.version

Signed-off-by: ignacy.ruksza <ignacy.ruksza@ledatel.pl>
-----

Ld symbol of the mosquitto_property_copy_all has global bind now.

---

lib/socks_mosq.c

<arpa/inet.h> header is required to compile this source. Without it, WARNING is generated.
mosquitto/lib/socks_mosq.c: In function 'socks5__send':
mosquitto/lib/socks_mosq.c:156:22: warning: implicit declaration of function 'inet_pton' [-Wimplicit-function-declaration]
ipv4_pton_result = inet_pton(AF_INET, mosq->host, &addr_ipv4);
Signed-off-by: ChangJoon Lee <changjoon.lee@lge.com>
for us to be told …

Add missing header for QNX

---

lib/misc_mosq.c

I suggest to use a direct ANSI version of Win32 API with current data type i.e. "char". Optionally add TODO to upgrade it to UNICODE at some time...
-----

Fixed compilation error on Win32 UNICODE platform.

---

lib/net_mosq.c

Fixed paranoid VS2017 compilation error of uninitialized variable (was a warning before).

---

config.h

Fixed QNX compilation. QNX 6.5 supports _XOPEN_SOURCE=600 or less.

---

lib/loop.c

Restored QNX 6.5 compilation.
Asked to merge to the "develop" instead of "fixes".
-----

QNX has no pselect() either

---

apps/mosquitto_ctrl/CMakeLists.txt

Fix enclosing include brackets in cmake
Signed-off-by: Franz Auernigg <f.auernigg@commend.com>

Fix enclosing include brackets in cmake

---

client/pub_client.c
client/pub_shared.h

Fixes eclipse/mosquitto#1899
In stdin line mode, mosquitto_pub will continue running and accepting
input even if/when/after publishing fails.  This condition is reached
when it first successfully establishes a connection and the server later
is unreachable.
Exiting with a non-zero exit code allows for much easier health
monitoring when used in a long-running pipe.
Signed-off-by: Dan White <dan.white@valpo.edu>
fix/feature change in an issue. For simple bug fixes it is can be just …

mosquitto_pub: exit if server becomes unreachable and QOS > 0

---

CMakeLists.txt

Useful in case only the lib is needed.
Signed-off-by: Pierre Hallot <hallotpierre@gmail.com>

CMake: Make building the apps and plugins optional

---

apps/mosquitto_ctrl/Makefile

In a cross compile environment, these paths will be added elsewhere, and
in a local environment, they should already be covered by the system
compiler.  Simply drop them.
Signed-off-by: Karl Palsson <karlp@etactica.com>
- [x ] Have you signed the [Eclipse …

apps: mosquitto_ctrl: don't hard set paths

---

man/mosquitto.conf.5.xml
mosquitto.conf
service/systemd/mosquitto.service.notify
service/systemd/mosquitto.service.simple

Fix Issue #1950  Systemd services would not start due to attempt to create pid file in directory that does not exist.  Script updated to create directory with correct privs.
-----

Systemd service changes for updated pid path

---

CMakeLists.txt

Fix appending to CMAKE_MODULE_PATH when a path already exists.  
Remove setting CMAKE_LEGACY_CYGWIN_WIN32 which is not needed anymore since CMake 3.0 is required.  
Set `project` after `cmake_minimum_required` as described in the documentation.
-----

Fix issue with CMAKE_MODULE_PATH

---

plugins/dynamic-security/Makefile
plugins/message-timestamp/Makefile
plugins/payload-modification/Makefile

Use the libdir variable from config.mk just like lib/ uses to ensure
that the plugins are installed into the same location as the library.
This fixes systems that use lib64 for libraries like most 64 bit
Linux distributions.
Signed-off-by: Peter Robinson <pbrobinson@gmail.com>
Then please check the following list of things we ask for in …

Use libdir as the install prefix for plugins

---

CMakeLists.txt

**It fails before and after my fix, I don't have cJson installed.**
-----
Fix cmake not building correctly when WITH_CJSON=OFF. 
In the main CMakeLists.txt, the cJson discovery process is executed regardless if WITH_CJSON is ON or OFF, this MR fixes that.
This …

Fix cmake not building correctly when WITH_CJSON=OFF

---

mosquitto.conf
src/bridge.c
src/conf.c
src/mosquitto_broker_internal.h

The use of TCP keepalive can be useful in some bridged scenarios. This PR allows the user to enable the mechanism and set these values (mapping setsockopt):
- idle
- interval
- counter
-----
-----

TCP keepalive for bridges

---

src/net.c

-----
Hi Mosquitto developers,
While upstepping this component, we noticed a regression in the interface binding of the broker.
More specifically: the commit 886ee6cd0c647e26b7c2a9f9f62cb181df3d5de3 changed the interface binding behavior from using …

Fix and improve interface binding

---

src/bridge.c

Current decorrelated jitter backoff mechanism for bridged connections  only applies for connectivity (network) issues. It fails to provide any kind of backoff in cases where the remote broker rejects the connection. This happens because the backoff timer gets prematurely reset before the actual CONNACK gets processed.
This PR fixes that
-----
-----

brige: fix backoff not working properly when remote broker rejects connection

---

src/database.c
src/handle_publish.c
src/mosquitto_broker_internal.h

Signed-off-by: Vidar Madsen <vidarino@gmail.com>
We're running several Mosquitto instances with bridges between them. At one point one of the bridges stopped working - it disconnected and reconnected repeatedly, never getting messages through, Upon further investigation, we concluded that the following had happened:
1. Broker1 sends a QoS2 message to Broker2.
2. At some point during the PUBREC/PUBREL/PUBCOMP exchange, Broker1 was restarted, and persistent storage was cleared.
3. Broker2 now sits on a stored copy of the message.
4. Broker1 reconnects and proceeds to send messages.
5. Broker1 later sends a QoS1 message with the same ID as in step 1
6. Broker2 finds the old QoS2 message ID in storage and proceeds to reply with a PUBREC.
7. Broker1 receives the PUBREC, but expects a PUBACK …

Handle stale stored messages with conflicting message IDs.

---

ChangeLog.txt
lib/connect.c
lib/handle_connack.c
lib/messages_mosq.c
lib/messages_mosq.h

On recent libmosquitto versions, messages on the output queue are sent twice, one time between CONNECT and CONNACK, and another time after CONNACK.
Bisecting the code changes, I was able to pinpoint the issue being introduced at: 298d84941ed673ea386c886bb9dda9b0ed18cc61
This pull request fixes the issue by avoiding resetting the state of the queued messages during CONNACK.
-----
-----

fix duplication of messages during connect

---

lib/loop.c

In commit a3ebeff9d732458a4dac7513fac10a52a97cf4d1 libmosquitto starting misbehaving during backoff. The new behavior, a total skip of the backoff, could be seen when messages were in the output queue.
This was fixed in f8838243fbb9689ce4195a6fbbb499ba477d1c65. This pull request is an improvement on top of that fix, by guaranteeing sockpairR is totally empty before waiting on it.
-----
-----

Fully empty sockpairR on interruptible_sleep

---

src/conf.c

This is a quick fix for a stranded "ignore config reload" on bridge settings. Bridge config reload has been supported for a while.
Though a fix, this PR is made to develop, as the code it fixes only exists there.
-----
-----

bridge: enable reload of bridge_bind_address

---

lib/mosquitto_internal.h
lib/net_mosq.c
lib/options.c
man/mosquitto.conf.5.xml
mosquitto.conf
src/bridge.c
src/conf.c
src/mosquitto_broker_internal.h

Current configuration of bridges does not allow specifying ciphers, this PR adds support for it.
TLS 1.3 requires using SSL_CTX_set_ciphersuites instead of SSL_CTX_set_cipher_list, this PR also covers that.
Updated documentation.
-----
- [N/A] If you are contributing a bugfix, is your work based off the fixes branch?
-----

add cipher settings for bridge, and support for TLS 1.3 ciphers

---

lib/send_publish.c
src/bridge.c
src/bridge_topic.c
src/conf.c
src/mosquitto_broker_internal.h

These commits modifiy the storage of topics associated with a bridge from:
a fixed size array allocated at config parse time
to: 
a linked list which can be modified after config time without reallocating
These changes are required to enable upcoming work on 'transitive topics'.

Swap bridge topic storage from array to linked-list

---

docker/1.5-openssl/Dockerfile
docker/1.5/Dockerfile
docker/1.6-openssl/Dockerfile
docker/1.6/Dockerfile
docker/2.0-openssl/Dockerfile
docker/2.0/Dockerfile
docker/generic/Dockerfile
docker/local/Dockerfile

As reported in #1211, Firefox cannot connect over websocekts with TLS when using HTTP2. Without HTTP2 support in libwebsockets the connections fallback to HTTP and are able to complete.
This work around has been successfully used by multiple commenters and tests well. This pull requests implements the work around when building Docker images.
Signed-off-by: Tom Parker <tparker@usgs.gov>

Disable HTTP2 when building libwebsockets for docker images.

---

lib/loop.c

When using the library asynchronously, TLS errors caused e.g. because
of the date/time not set correctly, cause the connection to be silently
dropped without the disconnection callback being invoked, as described
in issue #1052
This commit fixes the issue, returning the behavior to the one the
library had previous to version 1.5.4, if a TLS error occurs, the
disconnect callback will be invoked for the client to get notified of
the error.

Call disconnect callback on TLS error.

---

plugins/dynamic-security/CMakeLists.txt

On Windows MODULE will be installed as LIBRARY component
to `lib` folder that is not prefer for dynamic loaded modules
but can be found in RUNTIME DESTINATION (`bin` folder) too.
Partially closes #2371
-----

Fix DESTINATION for mosquitto_dynamic_security MODULE

---

src/plugin.c

The MOSQ_EVT_MESSAGE callback offers the flexibility to modify not only the payload, but also the topic. I might be missing something, but I believe the topic should receive the same treatment as the payload. Old memory should be freed in cases where the plugin intends to replace the topic. This PR implements that change.
-----
Then …

Fix memory leak when modifying topics using the plugin API

---

src/plugin.c
test/broker/09-plugin-tick.py
test/broker/c/Makefile
test/broker/c/auth_plugin_v5_handle_tick.c
test/broker/test.py

This should fix that plugins don't get tick events if the config file has the "per_listener_settings" set to true.
I added some tests for the ticks feature. I hope they match with the code standard.
-----
-----

support plugin tick callbacks with per_listener_settings config enabled

---

apps/mosquitto_ctrl/dynsec.c
include/mosquitto_broker.h
man/Makefile
plugins/common/plugin_common.c
plugins/common/plugin_common.h
plugins/dynamic-security/Makefile
plugins/dynamic-security/clients.c
plugins/dynamic-security/config_init.c
plugins/dynamic-security/control.c
src/linker.syms
src/plugin_public.c
test/broker/14-dynsec-client.py
test/broker/14-dynsec-disable-client.py
test/broker/14-dynsec-group.py
test/broker/14-dynsec-modify-client.py
test/broker/14-dynsec-role.py

For the dynsec plugin it would be helpfull to get a list of the connections for a given username. This way it's possible to check, which connections are using a give username (e.g will be disconnected when changing this user)
-----

Add list of connections to dynsec plugin listClients/getClient response

---

src/conf.c

The default bridge configuration uses the backoff restart configuration, however this is not cleared if only a constant timeout is desired, causing it to always use the backoff configuration with a 30 second cap.
To trigger this error, use a bridge configuration with a constant timeout (e.g restart_timeout 5). Note that the timeout value is not honoured. 
Clear the backoff configuration when applying restart_timeout.
Signed-off-by: Trevor Luscombe <trevor.luscombe@gmail.com> …

Fix constant restart_timeout

---

man/mosquitto.conf.5.xml
mosquitto.conf
src/bridge.c
src/conf.c
src/mosquitto_broker_internal.h

This PR delivers 4 things related to bridge backoff:
- Add an optional connection _stable_ period before resetting the backoff
- Move backoff internals to milliseconds to improve spread in case of remote broker restart
- Fix regression that makes impossible to achieve constant backoff
- Minor fix to documentation example inconsistency
-----
for us to be told about the problem and then go fix it …

Bridge backoff improvements

---

include/mosquitto_broker.h
src/linker-macosx.syms
src/linker.syms
src/plugin_public.c

Signed-off-by: Tobias Assarsson <tobias.assarsson@gmail.com>
-----
This is an implementation for feature request #2033
There seem to be some missing flags here and there to add include path for vendored uthash, unrelated to this PR.
I did not include any of …

Add `mosquitto_set_clientid` function for plugins.

---

CMakeLists.txt
man/CMakeLists.txt

When mosquitto is included as subdirectory, `CMAKE_SOURCE_DIR` does not refer to the mosquitto top level CMake file, but to the whole project top level CMake.
Use `PROJECT_SOURCE_DIR` instead to refer to the right CMake in both contextes.
Signed-off-by: Pierre Hallot <hallotpierre@gmail.com>

CMake: Use PROJECT_SOURCE_DIR to improve using mosquitto as subdirectory

---

src/bridge.c
src/conf.c

Pull request #2422 changed bridge backoff to count time in milliseconds. Though the configuration file parser was modified to take this into account, the default values were forgotten.
This PR fixes that change, which is currently only on develop
-----
Signed-off-by: Abilio Marques <abiliojr@gmail.com>
Then please check the following list …

fix default bridge backoff periods (scale seconds to milliseconds)

---

client/client_shared.c
client/sub_client_output.c
man/mosquitto_sub.1.xml

with the except for:
- 01-server-redirect.c (file does not exist, but is in Makefile)
- 02-subscribe-qos1.py (test hangs for me for unknown reason)
Both tests fail also without patch (clean devel branch) and patch is unrelated to these tests.
-----
More info …

mosquitto_sub: add support to print floats

---

plugins/persist-sqlite/init.c
plugins/persist-sqlite/persist_sqlite.h
plugins/persist-sqlite/plugin.c
plugins/persist-sqlite/test.conf
plugins/persist-sqlite/tick.c

This PR:
- Adds option to configure the flush period
- Adds option to configure the sqlite3 page size
- Fixes page_size setup by moving `PRAGMA page_size = ...` to it happens before setting the journal_mode to WAL
The default page_size still is 32KB (far from the 4KB SQLite's default). Unless the broker is always writing close to that size continuously, it actually causes 8x flash wear without huge performance improvements. Maybe 4KB should be the default, and can be tuned on an application basis
-----
If you aren't able to do that, or just don't want to, …

Add flush_period and page_size options to persist-sqlite

---

lib/loop.c

next_msg_out must be protected with the msgtime_mutex
as done everywhere else in the code else there is a data race
e.g. if mosquitto_publish is called from another thread
Signed-off-by: Christian Salvasohn <csalvasohn@gmx.de>
-----

fix data race mosquitto_loop function

---

ChangeLog.txt
src/conf.c
src/mosquitto.c
src/mosquitto_broker_internal.h

Allow broker users to test their configuration file before they reload it, by using the command line switch `--test-config`. This was requested by a user in  #2521.
-----
-----

broker: add command line argument to test configuration and exit

---

src/plugin.c

A while ago I was using the payload modification functionality, and spotted a memory leak. Completely missed other 2 leaks:
- If the plugin replaces the list of properties
- If there is more than one plugin chained
This PR fixes those leaks.
-----
-----

fix more memory leaks on plugin payload modification

---

CMakeLists.txt

To enable or disable tests in the build step and to circumvent the
CUnit build dependency.
Signed-off-by: Kai Buschulte <kai.buschulte@cedalo.com>
-----

Introduce a CMake WITH_TESTS option

---

apps/mosquitto_ctrl/Makefile
common/misc_mosq.c
common/misc_mosq.h
plugins/dynamic-security/config.c
src/persist_write.c

Implemented helper function to avoid double implementation of failsafe creation of data files. In the redundant implementation in the dynamic security plugin not all error cases were handled.
Signed-off-by: Norbert Heusser <norbert.heusser@cedalo.com>
-----

Created new helper function mosquitto_write_file to consolidate file writing

---

CMakeLists.txt
ChangeLog.txt

Makefiles already support an option to enable link time optimizations.
This is now also possible in CMake by using the WITH_LTO option.
It's turned on by default if the compiler supports these flags.
Note: LTO is part of the inter-procedural optimization (IPO).
Signed-off-by: Kai Buschulte <kai.buschulte@cedalo.com>
Then please check the …

Enable CMake LTO/IPO support (WITH_LTO option)

---

src/websockets.c

I know you've added this for the **next** release, but here is a fix for LWS, just in case there are any more 2.0.x releases.
It does leave the incoming port as 0 but as this is pretty meaningless for a proxied connection I think it's probably ok.
-----

Add support for X-Forwarded-For LWS

---

include/mosquitto.h

-----
Hi, i learned that:
Client send PINGREQ message to broker if no other messages have been exchanged within keepalive seconds, broker response with PINGRESP message. 
And If the borker does not receive any message from the client within 1.5 * keepalive …

Fix comments errors, it is the client that sends PING to broker actively

---

plugins/dynamic-security/README.md

mosquitto_ctrl example for setClientId was provided with wrong example (duplicate of setClientPassword).
-----

Correct a wrong example

---

mosquitto.conf
src/CMakeLists.txt
src/conf.c
src/logging.c
src/mosquitto_broker_internal.h

Add `log_dest` `android` in order to forward logs into the Android logging system (`logd`). Link `liblog` (included in each Android NDK) if building for Android. Add configuration note about log_dest android to configuration template.
Signed-off-by: Felix Obenhuber <felix.obenhuber@esrlabs.com>

Add android logd logging support

---

lib/property_mosq.c

-----
mosquitto_property_copy_all crashes if it tries to copy a string property with an empty string value due to null passed to strdup

Fixed empty string crash in mosquitto_property_copy_all

---

src/logging.c
src/sys_tree.c

system with 'make WITH_TLS=no WITH_CJSON=no WITH_DOCS=no'
Signed-off-by: Rob Swindell <rob@synchro.net>
-----

Fix build error: expected ‘)’ before ‘PRIu64’

---

lib/options.c

When calling mosquitto_tls_opts_set() multiple time in a row on the same mosquitto context (Example: trying to reconnect to mqtt broker), some of the tls options are not free, resulting in a memory leak.
The TLS options (tls_version, tls_ciphers) must be free before being set.

Fix memory leak in mosquitto_tls_opts_set()

---

man/CMakeLists.txt

Why not if xsltproc available?
Moreover why try to install not existent files?
Partially closes #2371
-----

Allow to build man pages on Windows

---

client/sub_client.c

Resolve win32 build Error C2440 with CALLBACK function decoration

---

lib/mosquitto.c
lib/time_mosq.c

This is just a minor fix for #2760

use CLOCK_BOOTTIME when available.

---

src/net.c

fixed a bug where the mosquitto-broker's private-key file(.pem)
dose not load with tls-engine.
Signed-off-by: Hyeongon Kim [khyeongon@gmail.com](mailto:khyeongon@gmail.com)
-----
fixed a bug where the mosquitto-broker's private-key file(.pem) dose not load …

fixed a bug where broker's private-key file was not loaded

---

man/mosquitto_ctrl.1.xml

This was reported by debian lintian checker
-----

man: Fix typo-in-manual-page noticable noticeable

---

src/conf.c

Parsing "bridge_tcp_user_timeout" configuration value is done under 'TCP_USER_TIMEOUT' define but is should be 'WITH_TCP_USER_TIMEOUT' instead as the latter used everywhere.

Fix define to properly parse bridge tcp user timeout configuration

---

src/subs.c

This small patch fixes sub_count is not decreased when client ubsubscribe.
-----

Fix sub_count is not decreased when client ubsubscribe

---

apps/mosquitto_ctrl/options.c
client/client_shared.c
lib/options.c
man/mosquitto.conf.5.xml

This small patch fixes two outstanding issues with OpenSSL engine support in the MQTT client:
1. When the tls_keyform is "engine" then the "keyfile" representing the private key is not neccessarily a real file but can be any handle known to the engine (URL, number, ...).
When the keyfile argument is validated in the function `mosquitto_tls_set()` then it should not be tried to open this file unless tls_keyform is "pem".
Because the tls_keyform must be known before calling `mosquitto_tls_set()`, the parsing of this tls_keyform config setting needs to be done before parsing the capath/cafile settings. 
2. Dynamically loadable OpenSSL engines require the `OPENSSL_INIT_ENGINE_DYNAMIC` option to be set or the `ENGINE_by_ID()` call will fail to find the engine in `mosquitto_string_option()`. As …

Fix engine keyfile support.

---

lib/CMakeLists.txt

Add dynamic symbols linking with cmake too

---

lib/strings_mosq.c

-----
fix #2579
Commit 6113eac95a9df634fbc858be542c4a0456bfe7b9 started using MQTT_RC_* enums as a handle__publish return value, which typically were MOSQ_ERR_* values. I personally think this is a good use, however the logging system should comply with it.

Increase logging of errors

---

lib/mosquitto.c
lib/time_mosq.c
lib/time_mosq.h

When the libc headers used to build mosquitto define CLOCK_BOOTTIME but the kernel where mosquitto runs does not implement CLOCK_BOOTTIME, all timestamps are wrong (uninitialized data), because there is no check for the success of the clock_gettime() calls.
This adds probing for the availability of CLOCK_BOOTTIME from mosquitto_lib_init(), falling back to CLOCK_MONOTONIC, and then modifies mosquitto_time() to use the selected clock. Probing at init time avoids having to do two clock_gettime() calls for every timestamp if CLOCK_BOOTTIME is not available.
It also fixes a similar problem in mosquitto_lib_init().
This fixes #3089 
you haven't signed the …

fix CLOCK_BOOTTIME use on kernels not having it

---

src/CMakeLists.txt

see: https://github.com/eclipse/mosquitto/pull/2751
Patch contributed by Joachim Zobel <jz-2017@heute-morgen.de> and  Daniel Engberg <daniel.engberg.lists@pyret.net>

Link correctly with shared websockets library if needed

---

lib/actions.c
lib/callbacks.c
lib/connect.c
lib/handle_connack.c
lib/handle_pubackcomp.c
lib/handle_publish.c
lib/handle_pubrec.c
lib/handle_pubrel.c
lib/handle_suback.c
lib/handle_unsuback.c
lib/logging_mosq.c
lib/loop.c
lib/messages_mosq.c
lib/mosquitto.c
lib/pthread_compat.h
lib/srv_mosq.c
lib/thread_mosq.c

In v2.020 pthread defines was renamed to "COMPAT_" and functions are not changed in all required places causing build failure.
-----

Fix for issue 3239. Added COMPAT_ prefix to pthread_ calls

---

src/net.c
test/broker/readme.txt

-----
Configuring a listener with bind_interface on an interface with an ipv6 link-local address causes Mosquitto to exit with "Error: invalid argument". This happens due to the the IPv6 scope ID not being copied to the returned addrinfo struct when resolving …

Copy scope id when binding to IPv6 Link-Local address

---

www/pages/documentation/dynamic-security.md

the cli arguments in the example went out of sync with the actual commands certfile -> cert and keyfile -> key
-----
Unfortunately I have not done that, if that is however required maybe someone with appropriate permissions can just do the "fix" in the …

Update dynamic-security.md (example code)

---

apps/db_dump/db_dump.c

Building mosquitto for Android using NDK r25 is working fine. But, when updating to r27 the following error is raised: 
> [ 79%] Linking C executable mosquitto
[ 79%] Built target mosquitto
[ 80%] Building C object apps/db_dump/CMakeFiles/mosquitto_db_dump.dir/db_dump.c.o
/home/builder/devopsagent/_work/521/s/mosquitto/apps/db_dump/db_dump.c:480:16: error: call to undeclared function 'ntohl'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
480 |                 db_version = ntohl(i32temp);
|                              ^
1 error generated.
Adding <sys/endian.h> when build target is Android, fixes the issue. 
Before you go any further, please note that we cannot accept …

Added Android specific includes

---

include/mosquitto.h

The documentation was wrong, the properties argument is not ignored, instead an error is returned as can be seen here for example: https://github.com/eclipse-mosquitto/mosquitto/blob/master/lib/connect.c#L168
- [n/a] If you are contributing a new feature, is your work based off the develop branch?
- [n/a] Have you successfully run `make test` with your changes locally?
-----

Document that MOSQ_ERR_NOT_SUPPORTED is returned for more methods.

---

lib/util_topic.c
src/bridge_topic.c
src/handle_subscribe.c
test/broker/06-bridge-b2br-remapping.py
test/unit/util_topic_test.c

- [] If you are contributing a new feature, is your work based off the develop branch?
-----

Check zero length topics and topic filters

---

apps/mosquitto_ctrl/client.c
apps/mosquitto_ctrl/mosquitto_ctrl.h
apps/mosquitto_ctrl/options.c
man/mosquitto_ctrl.1.xml

mosquitto_ctrl changes automatically to TLS mode if you use port 8883 like mosquitto_* clients #2541

---

plugins/persist-sqlite/base_msgs.c
plugins/persist-sqlite/clients.c
plugins/persist-sqlite/init.c
plugins/persist-sqlite/persist_sqlite.h
src/database.c
src/mosquitto.c
src/mosquitto_broker_internal.h
src/plugin_public.c
src/retain.c
src/session_expiry.c
test/broker/15-persist-bridge-queue.py
test/broker/15-persist-client-drop-expired-messages.py
test/broker/15-persist-client-expired-session.py
test/broker/15-persist-client-msg-modify-acl.py
test/broker/Makefile
test/broker/mosq_test_helper.py
test/broker/persist_module_helper.py
test/broker/persist_sqlite.py
test/mosq_test.py
test/mqtt5_props.py
test/unit/broker/persist_read_stubs.c
test/unit/broker/subs_stubs.c

Fix persist plugin expiry

---

apps/db_dump/Makefile

This fixes db_dump build issue with old gcc (4.5.1)

Fixes db_dump build issue with old gcc (4.5.1)

---

lib/mosquitto.c

fix leakage of mosq->tls_engine and User SSL Context
