Mosquitto.podspec

Signed-off-by: Josip Cavar <josipcavar04@gmail.com>

CocoaPods support

---

config.mk
lib/Makefile
lib/cpp/Makefile
lib/objects.mk

This pull request includes two changes
1. Install the C static library
2. Build and install the CPP static library

Enhance bare makefile static library build

---

src/db_dump/db_dump.c

Db dump fixes

---

src/mosquitto.c

mosqPID_shutdown
mosqPID_reload
mosqPID_backup
mosqPID_vacuum
where PID is the PID of the mosquitto process

Signalling mosquitto process on Win32, using named events:

---

src/persist.c

Signed-off-by: Milan Tucic <tucic.milan@gmail.com>

Writing least significant byte of subscription QoS

---

src/db_dump/db_dump.c

Prepratory work for providing more filtering of the output dump.
This makes _no_ difference to the current behaviour, but makes it much
simpler for people who "need", for whatever reason, to hack some private
changes into the db_dump tool.
Signed-off-by: Karl Palsson <karlp@etactica.com>
Example (not suggested for upstreaming) usage of this simplification: https://github.com/remakeelectric/mosquitto/commit/41554d5dec7df610bc0eb638d48e57bc2354d003

db_dump: use objects to simplify printing

---

docker/1.4.10/README.md
docker/1.4.4/README.md
docker/1.4.8/README.md

This PR corrects the path to the configuration file.

Update docker config path

---

docker/1.4.10/README.md
docker/1.4.12/Dockerfile
docker/1.4.12/README.md
docker/1.4.12/docker-entrypoint.sh
docker/1.4.4/README.md
docker/1.4.8/README.md

added Dockerfile and other stuff for building docker image based on version 1.4.12.
In my tests this also fixes #336

Docker image for 1.4.12

---

man/mosquitto-tls.7.xml

Signed-off-by: Srikanth Anantharam <sria91@gmail.com>

added missing information to the mosquitto-tls manpage

---

man/mosquitto_passwd.1.xml

Signed-off-by: Srikanth Anantharam <sria91@gmail.com>

fixed a typo in the manpage

---

test/broker/08-ssl-bridge.conf

Fix 08-ssl-bridge.conf to dial localhost by ipv4.

---

src/handle_unsubscribe.c
test/broker/02-unsubscribe-invalid-no-topic.py
test/broker/Makefile

Fixed #665 .
Signed-off-by: Tatsuzo Osawa (toast-uz) .

Fix Unsubscribe with No Topic

---

ChangeLog.txt

Added ChangeLog for #667 .
Signed-off-by: Tatsuzo Osawa (toast-uz)

Add ChangeLog for #667

---

readme.md

Signed-off-by: Michael Heimpold <michael.heimpold@i2se.com>

readme: mention documentation build requirements

---

debian/mosquitto.init

Signed-off-by: Tifaifai Maupiti <tifaifai.maupiti@gmail.com>

Add CONFIG parameter.

---

src/handle_connect.c

Signed-off-by: Thomas Pedley <me@shallax.com>

Add LWT message logging.

---

client/sub_client_output.c

Signed-off-by: Tifaifai Maupiti <tifaifai.maupiti@gmail.com>

Fix _POSIX_C_SOURCE : 199309L to 200809L

---

src/mosquitto.c

#573 
Increase maximum connections using _setmaxstdio for windows.

Increase maximum connections (Windows) from 512 to 2048 (Maximum)

---

lib/net_mosq.c

-----
I haven't run `make test` as I only have a cross compile setup, where I've built openssl with `no-engine` passed to configure.

Fix build with OPENSSL_NO_ENGINE

---

CMakeLists.txt
src/CMakeLists.txt
src/logging.c

- [Yes] If you are contributing a new feature, is your work based off the develop branch?
- [NA] If you are contributing a bugfix, is your work based off the fixes branch?
- [Yes] Have you added an explanation of what your changes do and why you'd like us to include them?
- [Yes] Have you successfully run `make test` with your changes locally?
- [Yes] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [Yes] Do each of your commits have a "Signed-off-by" line, with the correct email address? Use "git commit -s" to generate this line for you.
-----
This commit is DLT logging implementation for automotive platform
DLT (Diagnostic Log and Trace) link is https://github.com/GENIVI/dlt-viewer …

Implement DLT logging

---

lib/mosquitto.h

Fix comment, these are option values, not error values.

Fix comment for option values

---

docker/1.5/README.md
docker/1.6/README.md
docker/local/README.md

Fix typos for READMEs in Docker directory

---

man/mosquitto.conf.5.xml

docs: Fix typo on man-page for mosquitto.conf

---

client/sub_client.c

Exit on no subscription

---

src/CMakeLists.txt

cmake: add ADNS enable/disable dynamic support

---

src/net.c

Since all resources are ready, do not need lookup again.
Signed-off-by: Michael Liu <michael.liu.point@gmail.com>
-----

Move SSL prepare and accept operations out of deep loop

---

lib/mosquitto.h
lib/mqtt_protocol.h

Variety of documentation updates.  All can be chosen individually if desired.  Changes to the autogenerated output only, no code changes.
> (Could be considered a fix really, but it's currently based on develop)
> no, but I've run "make api" :)
-----

Documentation generation tweaks and improvements

---

lib/mosquitto.h

Patches are against the fixes branch, but should be equally applicable to develop.  Just minor cleanup of the generated library api docs

Docs regroup

---

lib/net_mosq_ocsp.c
lib/tls_mosq.c

Fixed "config.h" file placement to help using it as a precompiled header.

---

lib/loop.c

Something bad happened with a "timeout" parameter of mosquitto_loop() function.

---

src/CMakeLists.txt

Otherwise, if the package is not installed, configuration will work, but building will fail.
-----

CMake: Find package libwebsockets if the option is ON.

---

man/CMakeLists.txt

Signed-off-by: Pierre Hallot <hallotpierre@gmail.com>
-----

Look for xsltproc when needed; to fail early

---

man/mosquitto.conf.5.xml
src/bridge.c
src/conf.c
src/loop.c
src/mosquitto_broker_internal.h
test/broker/06-bridge-config-reload.py
test/broker/Makefile
test/broker/test.py

Allow bridges' configuration to be reloaded.
-----

feature: allow bridge config to be reloaded

---

plugins/auth-by-ip/CMakeLists.txt
plugins/dynamic-security/CMakeLists.txt
plugins/message-timestamp/CMakeLists.txt
plugins/payload-modification/CMakeLists.txt

CMake: Fix undefined symbols in plugins

---

man/mosquitto.conf.5.xml
mosquitto.conf
src/bridge.c
src/conf.c
src/mosquitto_broker_internal.h

Please find the description of this change in #2230

Support for bridge tcp user timeout option

---

src/handle_connack.c

Signed-off-by: Abilio Marques <abiliojr@gmail.com>
-----

fix confusing log message on connack error

---

apps/mosquitto_ctrl/CMakeLists.txt
apps/mosquitto_passwd/CMakeLists.txt
plugins/dynamic-security/CMakeLists.txt
plugins/examples/add-properties/CMakeLists.txt
plugins/examples/auth-by-ip/CMakeLists.txt
plugins/examples/client-lifetime-stats/CMakeLists.txt
plugins/examples/client-properties/CMakeLists.txt
plugins/examples/connection-state/CMakeLists.txt
plugins/examples/delayed-auth/CMakeLists.txt
plugins/examples/force-retain/CMakeLists.txt
plugins/examples/message-timestamp/CMakeLists.txt
plugins/examples/payload-modification/CMakeLists.txt
plugins/examples/payload-size-stats/CMakeLists.txt
plugins/examples/plugin-event-stats/CMakeLists.txt
plugins/examples/print-ip-on-publish/CMakeLists.txt
plugins/examples/topic-modification/CMakeLists.txt
plugins/examples/wildcard-temp/CMakeLists.txt
plugins/persist-sqlite/CMakeLists.txt
src/CMakeLists.txt

* Addded missing files plugin_subscribe and plugin_unsubscribe to src/CMakeLists.txt
* Aligned mixed usage of all-keyword and all-plain in target_link_libra…ry definition in in CMakeLists.txt
-----

Fixed CMakeLists.txt files

---

www/pages/documentation/dynamic-security.md

Fix typo (missing word)

---

client/pub_client.c

Don't reuse topic alias after reconnect.

---

test/broker/01-connect-global-max-clients.py
test/broker/01-connect-global-max-connections.py
test/broker/01-connect-max-connections.py
test/broker/02-subpub-qos0-long-topic.py
test/broker/02-subscribe-invalid-utf8.py
test/broker/02-subscribe-long-topic.py
test/broker/03-publish-invalid-utf8.py
test/broker/03-publish-long-topic.py
test/broker/03-publish-qos2-max-inflight-exceeded.py
test/broker/07-will-delay-invalid-573191.py
test/broker/07-will-invalid-utf8.py
test/broker/07-will-no-flag.py
test/broker/07-will-null-topic.py
test/broker/09-extended-auth-single.py
test/mosq_test.py

instead of ignoring this error, we throw an exception
the previous way might cause hard to find issues
Signed-off-by: Kai Buschulte <kai.buschulte@cedalo.com>
-----

throw BrokenPipeError if nothing received on socket

---

apps/mosquitto_ctrl/CMakeLists.txt
apps/mosquitto_passwd/CMakeLists.txt
client/CMakeLists.txt
lib/CMakeLists.txt
lib/cpp/CMakeLists.txt
plugins/dynamic-security/CMakeLists.txt
plugins/examples/add-properties/CMakeLists.txt
plugins/examples/auth-by-ip/CMakeLists.txt
plugins/examples/client-lifetime-stats/CMakeLists.txt
plugins/examples/client-properties/CMakeLists.txt
plugins/examples/connection-state/CMakeLists.txt
plugins/examples/delayed-auth/CMakeLists.txt
plugins/examples/force-retain/CMakeLists.txt
plugins/examples/message-timestamp/CMakeLists.txt
plugins/examples/payload-modification/CMakeLists.txt
plugins/examples/payload-size-stats/CMakeLists.txt
plugins/examples/plugin-event-stats/CMakeLists.txt
plugins/examples/print-ip-on-publish/CMakeLists.txt
plugins/examples/topic-modification/CMakeLists.txt
plugins/examples/wildcard-temp/CMakeLists.txt
plugins/persist-sqlite/CMakeLists.txt
src/CMakeLists.txt

CMake libmosquitto public include & cleanup

---

lib/cpp/mosquittopp.cpp
src/plugin_persist.c

Add missing callback set calls for MQTTv5 in C++ lib wrapper

---

plugins/examples/deny-protocol-version/CMakeLists.txt
plugins/examples/payload-ban/CMakeLists.txt

Signed-off-by: Kai Buschulte <kai.buschulte@cedalo.com>
-----

Fix CMake build

---

lib/mosquitto_internal.h
src/handle_connect.c
src/plugin_public.c
src/subs.c

Fix mosquitto_client_sub_count()

---

test/broker/16-config-missing.py
test/broker/16-config-parse-errors-without-tls.py
test/broker/Makefile

Signed-off-by: Norbert Heusser <norbert.heusser@cedalo.com>
-----

Extend broker tests for config errors

---

plugins/examples/plugin-event-stats/mosquitto_plugin_event_stats.c
src/database.c
src/mosquitto.c
test/lib/c/01-con-discon-success-v5.c
test/lib/c/02-subscribe-qos1-async2.c
test/unit/datatype_read.c
test/unit/keepalive_test.c
test/unit/property_add.c
test/unit/property_read.c

Fix compiler warnings

---

man/mosquitto_sub.1.xml

Repeated line:
<listitem><para><option>%I</option> ISO-8601 format date and time, e.g. 2016-08-10T09:47:38+0100</para></listitem>

Removed repeated line

---

plugins/dynamic-security/README.md

The invalid JSON is answered with:
```json
{
"responses": [
{
"command":"Unknown command",
"error":"Payload not valid JSON"
}
]
}
```

fix example JSON

---

client/client_shared.h
common/password_mosq.h
lib/http_client.h
plugins/common/plugin_common.h
test/broker/c/mosquitto_plugin_v2.h
test/old/msgsps_common.h

Signed-off-by: Norbert Heusser <norbert.heusser@cedalo.com>
-----

Cleanup of include guard defines

---

.github/workflows/delete-old-workflow-runs.yml
plugins/dynamic-security/plugin.c

We need 4 more characters to store the suffix.
-----

Fix malloc size for file path

---

.gitignore

git: Ignore more generated files

---

src/context.c

Do not add outgoing bridge connection context to session expiry list

---

src/context.c
test/broker/06-bridge-remote-shutdown.py
test/broker/Makefile
test/broker/c/Makefile
test/broker/c/plugin_evt_persist_client_update.c
test/broker/test.py

Do not add outgoing bridge connection to session expiry list

---

include/mosquitto.h

Fix typo in function mosquitto_string_option doc closes #2919

---

docker/generic/Dockerfile

Add OCI Image Labels

---

src/Makefile
src/plugin_debug.c

The `plugin_debug.so` can be useful to understand auth plugin callbacks, but its build is currently broken.
-----

Fix build for plugin_debug.so

---

test/broker/data/FORBIDDEN.json

Add test for early check of RESERVED command with illegal remaining length

---

src/websockets.c

fix timout during long running http downloads

---

src/database.c

This is a trivial change removing two unused variables.
-----

Remove unused variables in `database.c`

---

docker/generic/Dockerfile

Removed a trailing space from OCI title label
